version: '3.8'
name: 'dalim-api-staging'

services:
    dalim_app:
        image: dalim_app_img
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile.staging
        container_name: dalim_app
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - .:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - public_image:/var/www/html/public/image
            - public_pdf:/var/www/html/public/pdf
        ports:
            - "${APP_PORT}:8000"
        develop:
            watch:
                -   action: sync
                    path: ./
                    target: /var/www/html
                    ignore:
                        - vendor/
                -   action: rebuild
                    path: composer.json

        depends_on:
            - mysql
        links:
            - mysql
        command: >
            sh -c "
            composer install &&
            php artisan migrate &&
            php artisan optimize:clear &&
            php artisan serve --host=0.0.0.0 --port=8000
            "

    mysql:
        image: mysql:latest
        build:
            context: ./docker/mysql
        container_name: dalim_mysql
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_NEW_USERNAME}
            MYSQL_PASSWORD: ${DB_NEW_PASSWORD}
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "${EXPOSE_DB_PORT}:3306"
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dalim_phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        ports:
            - "${PHPMYADMIN_PORT}:80"
        depends_on:
            - mysql

    nginx:
        image: dalim_nginx_img
        build:
            context: ./docker/nginx/staging
        container_name: dalim_nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/staging/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - dalim_app

volumes:
    db_data:
    public_image:
    public_pdf:
