name: 'dalim-api-prod'

services:
    dalim_app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile.prod
        container_name: dalim_app_${SUFFIX}
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=${APP_KEY}
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - .:/var/www/html
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - public_image:/var/www/html/public/image
            - public_pdf:/var/www/html/public/pdf
        ports:
            - "${APP_PORT}:8000"

        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:8.0.34-oracle
        build:
            context: ./docker/mysql
        container_name: dalim_mysql_${SUFFIX}
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_NEW_USERNAME}
            MYSQL_PASSWORD: ${DB_NEW_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "${EXPOSE_DB_PORT}:3306"
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: dalim_phpmyadmin_${SUFFIX}
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
        ports:
            - "${PHPMYADMIN_PORT}:80"
        depends_on:
            - mysql

    nginx:
        image: nginx:alpine
        build:
            context: ./docker/nginx/prod
        container_name: dalim_nginx_${SUFFIX}
        volumes:
            - .:/var/www/html
            - ./docker/nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "${NGINX_PORT}:80"
        depends_on:
            - dalim_app

volumes:
    db_data:
    public_image:
    public_pdf:
